/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type CreateNoteDto = {
  title?: string | null;
  body?: string | null;
};

export type EditNoteDto = {
  /**
   * @format int32
   */
  id?: number;
  title?: string | null;
  body?: string | null;
};

export type NoteDto = {
  /**
   * @format int32
   */
  id?: number;
  title?: string | null;
  body?: string | null;
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  lastUpdatedAt?: string;
};
