/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type AuthResponseDto = {
  token?: string | null;
};

export type CreateNoteDto = {
  title?: string | null;
  content?: string | null;
};

export type EditNoteDto = {
  /**
   * @format int32
   */
  id?: number;
  title?: string | null;
  content?: string | null;
};

export type LogInDto = {
  /**
   * @format email
   */
  email?: string | null;
  password?: string | null;
};

export type NoteDto = {
  /**
   * @format int32
   */
  id?: number;
  title?: string | null;
  content?: string | null;
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  lastUpdatedAt?: string;
};

export type NoteDtoPaginatedResult = {
  items?: NoteDto[] | null;
  /**
   * @format int32
   */
  pageIndex?: number;
  /**
   * @format int32
   */
  pageSize?: number;
  /**
   * @format int32
   */
  totalCount?: number;
  /**
   * @format int32
   */
  totalPages?: number;
};

export type ProblemDetails = {
  type?: string | null;
  title?: string | null;
  /**
   * @format int32
   */
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
} & {
  [key: string]: any;
};

export type RegisterUserDto = {
  /**
   * @format email
   */
  email?: string | null;
  password?: string | null;
};

export type SortType =
  | "byTitle"
  | "byContent"
  | "byCreationTime"
  | "byLastUpdateTime";
